server:
  port: 8081
  error:
    include-message: always
    include-binding-error: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timesphere_test?serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: root
  config:
    import: application-secret.yaml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    time-zone: Asia/Ho_Chi_Minh

logging:
  level:
    org:
      springframework:
        security: DEBUG
